# Generated by Django 5.1 on 2024-08-31 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default=8, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='car',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='name',
            field=models.CharField(default=1989, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(default=8, max_length=200),
            preserve_default=False,
        ),
    ]
