# Generated by Django 5.1 on 2024-09-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_car_user_car_model_car_name_car_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.TextField(default=77),
            preserve_default=False,
        ),
    ]
